# ===================================================================
#         Smart WebView v8 - CONFIGURATION FILE (MBAH GADGET FINAL)
# ===================================================================

build.application.id=com.mbah.gadget
build.version.code=12
build.version.name=8.0.5

# --- SDK Versions ---
build.sdk.compile=36
build.sdk.min=24

# --- URL Configuration ---
debug.mode=false
app.url=https://mbahgadget.co.id/
offline.url=file:///android_asset/web/offline.html
search.url=https://www.google.com/search?q=
external.url.exception.list=mbahgadget.co.id

# --- Feature Flags ---
feature.uploads=true
feature.camera.uploads=true
feature.multiple.uploads=true
feature.custom.css=false
feature.copy.paste=true
feature.pull.refresh=false
feature.progress.bar=false
feature.zoom=true
feature.save.form=false
feature.open.external.urls=true
feature.chrome.tabs=true
behavior.back.exits=false
feature.exit.dialog=true

# --- Permissions & Security ---
permissions.on.launch=NOTIFICATIONS,LOCATION
security.verify.ssl=true
security.block.screenshots=false
security.accept.thirdparty.cookies=true

# --- UI & User Agent ---
ui.orientation=0
ui.layout=0
ui.drawer.header=false
ui.splash.extend=false
agent.postfix.enabled=true
agent.postfix.value=MBAHGADGETAndroid
agent.override.enabled=false

# --- Analytics & Plugins ---
analytics.gtag.id=G-Y6Z29740PB
plugins.enabled=RatingPlugin,LocationPlugin,DialogPlugin,AdMobPlugin,JSInterfacePlugin,ToastPlugin,QRScannerPlugin,BiometricPlugin,ImageCompressionPlugin,OneSignalPlugin
plugins.playground.enabled=false

# --- KUNCI ID ONESIGNAL BARU MBAH GADGET ---
onesignal.app.id=e722a15b-0b07-4c82-a934-fcd0735704a2
