# ===================================================================
#        Smart WebView v8 - MAIN CONFIGURATION FILE (FINAL + ONESIGNAL)
# ===================================================================

# ===========================================
# ANDROID BUILD CONFIGURATION
# ===========================================
build.application.id=com.mbah.gadget
build.version.code=8
build.version.name=8.0.1

# --- SDK Versions ---
build.sdk.compile=36
build.sdk.min=24

# ===========================================
# APP CONTEXT CONFIGURATION
# ===========================================
# --- Debug & Development ---
debug.mode=false

# --- URL Configuration ---
app.url=https://mbahgadget.co.id/
offline.url=file:///android_asset/web/offline.html
search.url=https://www.google.com/search?q=

# DAFTAR PENGECUALIAN DOMAIN
external.url.exception.list=mbahgadget.co.id

# --- Feature Flags (true/false) ---
feature.uploads=true
feature.camera.uploads=true
feature.multiple.uploads=true
feature.custom.css=false
feature.copy.paste=true
feature.pull.refresh=false
feature.progress.bar=false

# KUNCI UTAMA: AUTO-RESPONSIVE DI SEMUA HP + TETAP BISA DICUBIT ZOOM MANUAL!
feature.zoom=true
feature.save.form=false
feature.open.external.urls=true
feature.chrome.tabs=true
behavior.back.exits=false
feature.exit.dialog=true

# --- Permissions ---
permissions.on.launch=NOTIFICATIONS,LOCATION

# --- Security ---
security.verify.ssl=true
security.block.screenshots=false
security.accept.thirdparty.cookies=true

# --- UI & Theme ---
ui.orientation=0
ui.layout=0
ui.drawer.header=false
ui.splash.extend=false

# --- User Agent ---
agent.postfix.enabled=true
agent.postfix.value=MBAHGADGETAndroid
agent.override.enabled=false
agent.override.value=Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Mobile Safari/537.36

# --- Analytics ---
analytics.gtag.id=G-Y6Z29740PB

# --- Plugins & Permissions ---
# OneSignalPlugin SUDAH SAYA SELIPKAN DI BARIS INI, BRO!
plugins.enabled=RatingPlugin,LocationPlugin,DialogPlugin,AdMobPlugin,JSInterfacePlugin,ToastPlugin,QRScannerPlugin,BiometricPlugin,ImageCompressionPlugin,OneSignalPlugin
plugins.playground.enabled=false

# --- Plugins Configuration ---
rating.install.days=3
rating.launch.times=10
rating.remind.interval=2
biometric.trigger.launch=false

# KUNCI SUKSES ONESIGNAL PUSH NOTIFICATION MBAH GADGET (SUDAH FIX)
onesignal.app.id=c3c2abac-1f8e-4867-ac2b-afcc92430ede
